py_library (
  name = "types",
  srcs = [
    "builtins.py",
    "parsed_target.py",
    "parser_host.py",
    "paths.py",
    "references.py",
  ],
  deps = [
    "//impulse/core:environment",
  ],
)