py_library(
  name = "types",
  srcs = [
    "builtins.py",
    "paths.py",
    "parser_host.py",
    "parsed_target.py",
    "references.py",
  ],
  deps = [
    ":typecheck",
    "//impulse/core:environment",
  ],
)

py_library(
  name = "typecheck",
  srcs = [
    "typecheck.py",
  ],
)