langs("Python")

py_library(
    name = "debug",
    srcs = [ "debug.py" ],
)

py_library(
  name = "exceptions",
  srcs = [ "exceptions.py" ],
)

py_library(
  name = "job_printer",
  srcs = [ "job_printer.py" ],
  deps = [ ":debug" ],
)