load(
    "//rules/core/Python/build_defs.py",
)


py_library(
  name="args",
  srcs=[
    "args.py",
  ],
)

py_test(
  name = "args_unittest",
  srcs = [
    "args_test.py",
  ],
  deps = [
    ":args",
  ]
)