langs("Python")

py_library (
  name = "temp_dir",
  srcs = ["temp_dir.py"]
)

py_library (
  name = "tree_builder",
  srcs = ["tree_builder.py"]
)

py_library (
  name = "interface",
  srcs = ["interface.py"]
)

py_library (
  name = "bintools",
  srcs = [ "resources.py" ],
  deps = [ ":temp_dir" ],
)

py_library (
  name = "temporal_dict",
  srcs = [ "temporal_dict.py" ]
)