platform (
  name = "x64-linux-gnu",
  cc_compiler = "g++",
  cc_linker = "ld",
  c_compiler = "gcc",
)

platform (
  name = "x64-linux-clang",
  cc_compiler = "clang++",
  cc_linker = "ld",
  c_compiler = "clang",
)