platform (
  name = "x64-linux-gnu",
  cc_compiler = "g++",
  cc_linker = "ld",
  cc_flags = [
    "-Wall", "-Wextra", "-Wpedantic", "-Werror",
    "-fdiagnostics-color=always",
  ],
  ld_flags = [],
  c_compiler = "gcc",
)

platform (
  name = "x64-linux-clang",
  cc_compiler = "clang++",
  cc_linker = "ld",
  c_compiler = "clang",
)

platform (
  name = "avr32-gnu",
  cc_compiler = "avr-gcc",
  cc_linker = "avr-ld",
)