load(
    "//rules/core/Python/build_defs.py",
)

impulse_py_binary(
	name = "impulse",
	srcs = [
		"__main__.py",
        "build_defs_runtime.py",
        "impulse.py",
        "impulse_paths.py",
        "recursive_loader.py",
        "status_out.py",
        "threaded_dependence.py",
	],
)