langs("Python")

py_library (
  name = "core_rules",
  deps = [
    "//impulse/rules/core/C:rules",
    "//impulse/rules/core/Golang:rules",
    "//impulse/rules/core/JS:rules",
    "//impulse/rules/core/Python:rules",
    "//impulse/rules/core/Shell:rules",
    "//impulse/rules/core/Template:rules",
  ],
  srcs = [
  ],
)