langs("Python")

py_library (
  name = "packaging",
  srcs = [
    "overlayfs.py",
    "packaging.py",
  ],
  deps = [
    "//impulse/core:exceptions",
    "//impulse/fuse:fuse",
    "//impulse/util:temp_dir",
  ],
)