langs("Python")

py_library(
  name="packaging",
  srcs=[
    "packaging.py",
    "overlayfs.py",
  ],
  deps=[
    "//impulse/fuse:fuse",
    "//impulse/exceptions:exceptions",
    "//impulse/util:temp_dir",
  ]
)