name: build impulse

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            fuse3 \
            fuse-overlayfs \
            libfuse-dev \
            python3 make

      - name: Verify fuse-overlayfs
        run: |
          which fuse-overlayfs
          fuse-overlayfs --help

      - name: Build Impulse
        run: make

      - name: Run Unit Tests
        run: ./GENERATED/BINARIES/impulse/impulse testsuite --fakeroot $(pwd) --project impulse
