name: build impulse

on:
  push:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Podman and dependencies
        run: |
          sudo apt-get install -y \
            fuse3 \
            fuse-overlayfs \
            libfuse-dev \
            python3 make

      - name: Verify fuse-overlayfs
        run: |
          which fuse-overlayfs
          fuse-overlayfs --help

      - name: Build impulse inside Podman using fuse-overlayfs
        run: make
